-- Hand-written. Prisma can generate the shapes but not the three things that
-- matter here: the backfill (which must read the old rows while they still carry
-- a status), the CHECK constraint, and dropping the partial index on purpose.
--
-- What changes and why:
--   * `Enrollment` becomes the registration — the roster is now a query about
--     who is registered, not about whose order was paid.
--   * `BookingItem.status` disappears: a booking is all-or-nothing, so the order
--     carries the state and this table records what was bought and at what price.
--   * `Booking_confirmed_unique` (the partial index on the items) is NOT
--     recreated. Its guarantee moves to Enrollment's plain UNIQUE(studentId,
--     classId), which needs no status predicate because a refunded registration
--     is deleted rather than marked. Do not read its absence as an oversight.
--   * `TrialClass` gains `description` and, for the first time, a database-level
--     range check on the seat counter.

PRAGMA foreign_keys=OFF;

-- 1. Park the current items. Their `status` is about to disappear, but the
--    backfill in step 4 still needs to know which lines were confirmed.
ALTER TABLE "BookingItem" RENAME TO "BookingItem_old";
DROP INDEX IF EXISTS "BookingItem_classId_status_idx";
DROP INDEX IF EXISTS "BookingItem_studentId_status_idx";

-- 2. The new items: no status. Indexes are now single-column, because the status
--    that used to be their second column is gone, and `bookingId` gains the one
--    it never had (items are always read per order).
CREATE TABLE "BookingItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "bookingId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "classId" TEXT NOT NULL,
    "price" DECIMAL NOT NULL,
    "confirmedAt" DATETIME,
    "refundedAt" DATETIME,
    "refundAmount" DECIMAL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BookingItem_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "BookingItem_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "BookingItem_classId_fkey" FOREIGN KEY ("classId") REFERENCES "TrialClass" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO "BookingItem" ("id", "bookingId", "studentId", "classId", "price", "confirmedAt", "refundedAt", "refundAmount", "createdAt")
SELECT "id", "bookingId", "studentId", "classId", "price", "confirmedAt", "refundedAt", "refundAmount", "createdAt"
FROM "BookingItem_old";

CREATE INDEX "BookingItem_classId_idx" ON "BookingItem"("classId");
CREATE INDEX "BookingItem_studentId_idx" ON "BookingItem"("studentId");
CREATE INDEX "BookingItem_bookingId_idx" ON "BookingItem"("bookingId");

-- 3. Registrations.
CREATE TABLE "Enrollment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "studentId" TEXT NOT NULL,
    "classId" TEXT NOT NULL,
    "bookingItemId" TEXT NOT NULL,
    "enrolledAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Enrollment_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Enrollment_classId_fkey" FOREIGN KEY ("classId") REFERENCES "TrialClass" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Enrollment_bookingItemId_fkey" FOREIGN KEY ("bookingItemId") REFERENCES "BookingItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "Enrollment_bookingItemId_key" ON "Enrollment"("bookingItemId");

-- The invariant the partial index used to carry, now expressed without a
-- predicate: a child is registered in a class at most once.
CREATE UNIQUE INDEX "Enrollment_studentId_classId_key" ON "Enrollment"("studentId", "classId");

-- 4. One registration per confirmed line, read from the parked table.
INSERT INTO "Enrollment" ("id", "studentId", "classId", "bookingItemId", "enrolledAt")
SELECT 'legacy_enr_' || b."id", b."studentId", b."classId", b."id", COALESCE(b."confirmedAt", b."createdAt")
FROM "BookingItem_old" b
WHERE b."status" = 'confirmed';

DROP TABLE "BookingItem_old";

-- 5. Classes gain a description, and the seat counter gains the range check it
--    never had — until now, "never oversold" was application logic only. SQLite
--    cannot add a CHECK in place, so the table is rebuilt. Prisma does not model
--    CHECK constraints, so a future rebuild generated by `migrate dev` would
--    drop this silently: re-add it if that day comes.
CREATE TABLE "new_TrialClass" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "subject" TEXT NOT NULL,
    "startsAt" DATETIME NOT NULL,
    "durationMin" INTEGER NOT NULL DEFAULT 60,
    "capacity" INTEGER NOT NULL DEFAULT 4,
    "confirmedCount" INTEGER NOT NULL DEFAULT 0,
    "price" DECIMAL NOT NULL DEFAULT 50,
    CONSTRAINT "TrialClass_seats_within_capacity" CHECK ("confirmedCount" >= 0 AND "confirmedCount" <= "capacity")
);

INSERT INTO "new_TrialClass" ("id", "title", "description", "subject", "startsAt", "durationMin", "capacity", "confirmedCount", "price")
SELECT "id", "title", NULL, "subject", "startsAt", "durationMin", "capacity", "confirmedCount", "price"
FROM "TrialClass";

DROP TABLE "TrialClass";
ALTER TABLE "new_TrialClass" RENAME TO "TrialClass";

PRAGMA foreign_keys=ON;
